name: Build
on:
  workflow_run:
    workflows: Tests
    branches: master
    types: completed
  workflow_dispatch:

jobs:
  check-changes:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      songs_have_changed: ${{ steps.songs-changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Check for changes in songs folder
        id: songs-changed
        uses: tj-actions/changed-files@v47.0.1
        with:
          files: songs/**
  build:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.songs_have_changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.SONGBIRD_APP_ID }}
          private-key: ${{ secrets.SONGBIRD_PRIVATE_KEY }}
      - uses: actions/checkout@v6.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Get commit message
        id: commit-title
        run: yarn --silent github commitTitle >> "$GITHUB_OUTPUT"
      - name: Commit build
        run: |
          git config --global user.name 'Songbird Bot'
          git config --global user.email 'itsektionen-webmaster@users.noreply.github.com'
          git add dist
          git commit -m "${{ steps.commit-title.outputs.out }}" \
          -m "Build was created as a result of commit ${{ github.event.workflow_run.head_commit.id }}" \
          -m "[skip actions]"
          git push
